services:
  - type: web
    name: trandangkhoatechnology-github-readme-stats
    runtime: node
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PAT_1
        sync: false
